export const ACTION_TYPES = {
    ADD_PLAYER: 'ADD_PLAYER',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
    EDIT_PLAYER: 'EDIT_PLAYER',
    ADD_POINTS: 'ADD_POINTS',
    RESET_ALL: 'RESET_ALL',
    NEW_GAME: 'NEW_GAME',
    LOAD_GAME: 'LOAD_GAME',
} as const;
